### ISSUE TITLE
Handle invalid or expired session keys to Hydrus

### ISSUE THREAD

**Issue by floogulinc** [ififfy/flipflip#260]
When using the Hydrus source, a session key can become expired or invalid in which case Hydrus responds with a 419 error. FlipFlip doesn't handle this and just shows "I couldn't find anything". 

Really you should not be using the session keys at all since you are already using the api key for the image urls so the session key isn't helping security in anyway. It would just be simpler to use the api key for all requests.

**Comment by professor-mesmerize** [comment]
I've run into this myself finally, as well. I took a look at the network console while it was happening, and there definitely seemed to be some pretty strange behavior - sometimes FlipFlip would show it's "couldn't find anything" error even when it got a proper 200 response from Hydrus. Sometimes just clearing FlipFlip's cache would fix it, sometimes just removing the Hydrus auth and then re-adding it in FlipFlip would fix it, but the only thing that seemed to reliably fix it was doing both?

(That said, I was admittedly doing some stuff with moving FlipFlip between displays and having a custom caching location combined with portable mode being on, so that could have also had something to do with it)

@StarrHelixx let me know if you want any help with this one! I've been getting more familiar with Hydrus and it's code and, while my javascript is still rusty, I could take a crack at fixing this one if that'd be helpful.

**Comment by StarrHelixx** [comment]
@professor-mesmerize I would _love_ some help with the Hydrus stuff, as I don't have a server setup myself, so I simply wrote the code with a bare-minimum understanding of how it works and a server from a member of the community. The Hydrus docs aren't as detailed as I'd like, so that didn't help.

The main chunk of code for Hydrus is located within [`SourceScraper`](https://github.com/ififfy/flipflip/blob/master/src/renderer/components/player/SourceScraper.tsx#L1463-L1583). The job of this method is to pass back a set of image/video URLs to be loaded by the next component. It sounds like there also might be an issue with caching for hydrus, so you might want to take a look at [this line](https://github.com/ififfy/flipflip/blob/master/src/renderer/components/player/SourceScraper.tsx#L143). Basically, this block tries to load the cache directory of a source _before_ loading the source itself. However, if the cache directory exists but is empty, I've seen FlipFlip respond with "I couldn't find anything". So it may make sense for Hydrus to make the conditional `(helpers.next == -1 && sourceType != ST.hydrus)`

**Comment by professor-mesmerize** [comment]
@StarrHelixx Gotcha, that's helpful info! I've got some time this evening, so let me see what I can do.

**Comment by floogulinc** [comment]
I'll mention this again, I highly recommend just removing any use of session keys in favor of just using the regular api key for all requests. There is no benefit in how it is currently using session keys and it would simplify it quite a bit.

**Comment by professor-mesmerize** [comment]
@floogulinc Yup, agreed - that's the first thing I'm going to try to do.
