### ISSUE TITLE
Play videos/animations in reverse

### ISSUE THREAD

**Issue by slickmeister** [ififfy/flipflip#281]
Hi, I've been looking for a video player that can play video backwards, but failed to do so.  

Then I thought maybe FlipFlip could implement it as an option, because it really adds a new dimension to the animation tools.

But I think I've read somewhere that digital video is hard to play in reverse? Is this true?

**Comment by StarrHelixx** [comment]
Because video is encoded as a stream, in order to play it backwards, it would first have to process the entire stream and then start serving frames backwards. This is particularly difficult in Electron (what FlipFlip is based on) because the HTML 5 Video element assumes playback is always forward. So, unfortunately, this is not a thing that FlipFlip is capable of.

If you're looking to play a video in reverse, I'd recommend using an [online tool](https://ezgif.com/reverse-video) to actually reverse the frames of the video file, and then play it back.
