### ISSUE TITLE
SourceScraper - TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by featherice** [ififfy/flipflip#323]
To reproduce a bug try to setup 3 scenes in a chain (Next scene for 1st is 2nd, for 2nd is 3rd, for 3rd is 1st). Then add a caption script which forces scene to end at random time:
`setBlinkDelayTF random
setBlinkDelay 6000 12000
blink TEST`
It works fine with 2 scenes.

FlipFlip Version: 3.2.1
```
TypeError: Cannot read property 'addEventListener' of null
in SourceScraper
    in Player
    in ErrorBoundary
    in Unknown
    in Meta
```

**Comment by StarrHelixx** [comment]
I was not able to reproduce the issue you described ... but this did bring my attention to a different bug which was preventing Caption scripts from continuing after 2 scenes. This has been fixed here: https://github.com/ififfy/flipflip/commit/e5185d747316fa0d5281e41a1a2f60cb5360ff34

I appreciate the detail, but I'll need more info to reproduce this because that setup worked for me.
