### ISSUE TITLE
Allow videos in slideshow

### ISSUE THREAD

**Issue by ififfy** [ififfy/flipflip#49]
TODO: 
- [x] Allow videos to be used as sources
- [x] Allow `ImagePlayer` to load video elements
- [x] Allow `ImageView' to display video elements
- [x] Ensure effects are maintained
- [x] Cache videos
- [x] Limit video min size
- [x] Improve Scraping
- ~~Add option for audio~~

**Comment by ififfy** [comment]
Treat them like gifs?

**Comment by GoddessServant0** [comment]
Are we also looking to support other video formats? MP4, MKV, AVI, etc.? This could get messy, but would be really cool!

**Comment by GoddessServant0** [comment]
Any ideas on how to do this @ififfy ? Been wanting to do this for awhile, would make experiences a lot cooler... but introduces a number of complications.

---
I was looking into somehow rendering video files as `<image>`, but looks like this only supported in Safari at the moment. So our other options are (1) rendering videos in '<video>' or (2) somehow converting videos to a format supported by `<image`> (likely `.gif`).

Personally, I'd rather render as `<video>`, but that involves ensuring playback effects work between `ImageView` and (hypothetical) `VideoView`. Converting segments to gifs would fit better with the current flow, but requires that additional processing on top of the extra space to store those gifs.

---
Regardless of rendering, obviously we don't want to show the whole video. Maybe we limit videos to those under 2 minutes and/or a certain byte size? Then select like 3 random 10-20 second segments to show? These could be configurable too.

---
Lemme know if you have any thoughts or ideas 😊

**Comment by ififfy** [comment]
The video tag will be necessary. Converting to gifs isn't feasible for a number of reasons. Videos should be able to preload.

I'm not sure I agree that we shouldn't show entire videos. We could put a time limit option on, but I can see how people would want to use a video playlist as an overlay to a slideshow.

Cross-fading and blur should still be possible.

**Comment by ififfy** [comment]
My suggestion for getting things working is to just spend some time getting a pair of videos to play and cross-fade between each other. Once you get that running I'd be happy to jump in and work on effects and such.

**Comment by GoddessServant0** [comment]
Ultimately, `ImagePlayer` would load them instead of an `Image`. But I can't seem to get video elements to load 😟 Or at least the `onload` event never seems to fire.

You can check out my [video_work](https://github.com/ififfy/flipflip/tree/video_work) branch. Maybe you can tell what I'm doing wrong? 🤔 I'm using this source to test: https://hastebin.com/raw/ekinerojer

This just references a 1MB test mp4: https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4

**Comment by GoddessServant0** [comment]
Figured out video elements throw `onloadeddata` and not `onload`. Attached correct listener, and at least getting videos to render at the moment. However, the `ImagePlayer` quickly renders again (not because of a Component update though 🤨) and then the video stops playing. Also it's not centered in the player (but I think `video` elements need a `canvas` for stuff like that)

I appended my branch

**Comment by GoddessServant0** [comment]
https://github.com/ififfy/flipflip/commit/b08a879f121ae33842ed36678aceb998f5e85875

TODO: 

- [ ] Improve Scraping
- [ ] Cache videos
- [ ] Limit video min size

**Comment by GoddessServant0** [comment]
I added filtering and caching back to video sources and improved the scrapers to get video links too

Twitter will need some adjustment because the current endpoint I'm using only provides links for images, not videos. Was looking into using an the Twitter oauth API like Tumblr/Reddit.

Spent some time trying to get audio to work, ended up being a nightmare of trying to get only the audio for the currently visible video to be playing. The browser handles muted videos very well! (Pausing and Resuming when the video goes off/on screen) But with audio playing, it just kept continuously playing _all_ loaded videos in the background 😳 If there is a high demand for this maybe we'll come back to it... but def not trivial
