### ISSUE TITLE
Include version number in data.json

### ISSUE THREAD

**Issue by f3lin3** [ififfy/flipflip#98]
**.config/flipflip/data.json**

1) Would there be any benefit in us putting a version number into the data.json file?
This might enable future upgrade maintenance should we wish to change the structure and contents of the serialized state data - between releases?

**Caching Folder Names**
2) Caching appears to be working well.  I wonder if there would be benefit in choosing folder names and structure which replicate the whole domain name and sub domain names? So for http://we-lovecats.tumblr.com/ - the folder structure in the cache could be:

com
  tumblr
    we-lovecats

If a user already has a collection of downloads then they can populate them in the correct cache folder - rather than having to start their library from scratch....

More over - the library feature - great as it is, could then be quickly synced with the cache structure.  So say I transfer to you my whole cache - you don't have to sit there and re-enter all the URLS to configure the library - we can code the library to know how to reconstruct /sync itself with the under-lying structure.

Also - I wonder if this would lend itself to a heuristic approach to scraping content - I enter into the library a URL of say  "https://goodcats.greatpictures.example.com   - the library knows to create a cache folder structure of 
com
  example
    greatpictures
        goodcats

or if the Library recognises that it does not have the URL but it already has the structure in the cache - it rebuilds the URL for the Library record...

now the heuristic part - presumably there will be a number of importers/scrapers - e.g. tumblr and now work on reddit - but even if there is not a specific importer/scraper for goodcars.greatpictures.example.com - we can try the importers one after the other - until going to the raw-est of all import mechanisms of hitting the page and wgetting or equivalent each image referenced ....

**Comment by GoddessServant0** [comment]
Linking this to #97 

(1)
@ififfy Can probably answer this better than myself. Personally, I don't care to continue to maintain a bunch of complicated backwards compatibility stuff. I purposely didn't take that into consideration during this first iteration for the sake of simplicity (and not making changes until the data structures are finalized), so we'll certainly have to add some statements to `Scene`'s constructor for v2.0 to work with older Scenes.

(2)
Currently, the cache already works pretty much like that. Structure is `<cacheDir>/<type>/<group>` where `type` is "tumblr", "reddit", etc. and `group` is the blog name, subreddit name, etc. 

Using this knowledge, users can (already) pre-populate the cache: just put all your tumblr dumps in `<cacheDir>/tumblr/`. Or put them in a dir called `tumblr` and set the cache dir as the parent directory ¯\_(ツ)_/¯

Because FlipFlip has no way of handling arbitrary URLs like ""https://goodcats.greatpictures.example.com", it doesn't benefit us really to implement arbitrary directory structure. Our "scraping" algorithms don't work on generic "galleries", because we are using very specific API methods for each service, so unless we have a specific method to handle a host, the URL is invalid. If, in the future, we add the ability to scrape arbitrary URLs, then this would be helpful. 

Concerning Import, we could definitely provide a nicer utility for that 👍 As a work-around for now, you can (1) hit Alt+P to bring up the gooninator import. This works with both local and Tumblr's now (just select the type you want). So if you want to import all your stuff, (2) move them to `<cacheDir>/tumblr`, (3) create a gooninator link with all the sources you want to upload (just needs to be `sources=<blog1>%20<blog2>%20<blog3>....`) and import. Now you have a library full of tumblr blogs, all which will serve the cache first 😄

**Comment by f3lin3** [comment]
1. - I take the points about the enthusiasm (or lack of) to maintain backwards compatibility - a version number dropped in however does leave the door more easily open for decisions to be taken in the future - but it is no big deal if @ififfy doesn't want one in. (I would note that including a version number might assist other (3rd party) software which might want to co-operate with flipflip - be it automation, configuration, import or export - but again the desirability to ease other's use of flipflip may be moot)

2. Yes, I recognise that specific APIs are being called, and that flipflip is not as yet implementing any front end generic image scraping or arbitrary URLs.  Were such functionality to be included in the future it would potentially then be usable against any website, and be the go-to APP for creating galleries of images of all websites.  (I also recognise that tech savvy users can currently pre-populate the v2.0 cache directories etc in the way you identify.)  

Nevertheless embedding the full URI into the cache nomenclature hierarchy may _arguably_ provide scope for increased future flexibility in the generic situations possibly with sites which use canonical URI names.  (either for geolocation,  branding, or censorship reasons etc) e.g. in the generic situation "example.net" and "example.org" might be canonical names for one site (possibly either slightly differently branded) and yet both may use the same API.  example.net, and example.org, may be different from example.ru  - although ultimately might conceivably be essentially the same site.  If the full name is included in the cache hierarchy decisions about about hard or soft folder/directory joining or linking of canonical named sites might then be possible to avoid duplicating downloads etc.  

However, neither of these points are big deals - as if they become future issues on the development path they can always be addressed at that stage.

**Comment by GoddessServant0** [comment]
> Were such functionality to be included in the future it would potentially then be usable against any website, and be the go-to APP for creating galleries of images of all websites.
Now _that's_ future thinking 😉😋

I'm not opposed to either of these ideas, I just probably won't be the one to implement them 😁 If you submit a PR at some point and everything still works correctly, I don't see any problem 👍

I kinda tossed the caching algorithm together, not my best work 😅 I tried implementing it such that old files were cleaned up as the cache filled up, but these would also have to be correctly removed from `allUrls` as well -- otherwise, `Player` would start to serve files no longer on the system. I just left it as it is for now, but that could definitely stand to be improved. Moreover... I couldn't figure out how to get the stream used by `Image.src`, so I'm making a _second_ request to download the file... also not ideal. But not sure how to fix that one.

**Comment by ififfy** [comment]
Caching is a complex topic, and doing anything more complicated will take more careful work than we have time for for 2.0.

I think having a "data file version number" is a great idea regardless of what older versions we intend to support. My backward compatibility efforts so far have mostly caused bugs, but I'd hate to delete people's data when they upgrade in the future.

**Comment by GoddessServant0** [comment]
@f3lin3 If you want to implement adding the version number to `data.json`, we can close this issue and open a general discussion on Caching implementation(s) for future versions 👍

**Comment by f3lin3** [comment]
The version number in package.json in the project is still on 1.2.0   - should it be updated to 2.0.0?

**Comment by GoddessServant0** [comment]
I did that too 👍 Closing

**Comment by GoddessServant0** [comment]
Re-opening: https://github.com/ififfy/flipflip/pull/110#issuecomment-462429352

> While this works in production builds - it doesn't when in electron is launched within a debugger.... I am looking at how to resolve this.... And then hopefully I can put some code in to convert a v1.2.0 data.json to v2.0.0 data.json so as not to lose the existing scenes on upgrading....

Yes, if you could ensure v1.2.0 scenes aren't blown away when the upgrade happens, that would be _fantastic_! 💕

**Comment by GoddessServant0** [comment]
Fixed
